language: c

before_install:
  - sudo add-apt-repository -y ppa:saiarcot895/chromium-beta
  - sudo apt-get update

install: sudo apt-get install ninja-build

script: ./configure && ninja -v

compiler:
  - gcc
  - clang
